language: shell
dist: xenial
cache:
  directories:
    - /home/travis/.cache/bazel/
os: linux
services:
  - docker
jobs:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
script:
   # On arm64, we need to create our own pipes for stderr and stdout,
   # otherwise we will not be able to open /dev/stderr. This is probably
   # due to AppArmor rules.
   - uname -a && make smoke-test
branches:
  except:
  # Skip copybara branches.
  - /^test\/cl.*$/
